services:
  - type: web
    name: codebuff-tricks
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    domains:
      - codebuff.nathanarthur.com
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
      - path: /_app/immutable/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /*.js
        name: Content-Type
        value: application/javascript
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
