services:
  - type: web
    name: codebuff-tricks
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./build
    pullRequestPreviewsEnabled: true
    domains:
      - codebuff.nathanarthur.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
